### ISSUE TITLE
(Minor) Import order in /core/planner.py

### ISSUE THREAD

**Issue by iliathesmirnov** [pyrddlgym-project/pyRDDLGym-jax#2]
https://github.com/pyrddlgym-project/pyRDDLGym-jax/blob/1bd28d480c3d75c2ea4deef0c3efa3c100433ddc/pyRDDLGym_jax/core/planner.py#L18

When handling the Exception, raise_warning is called. But raise_warning is not imported from pyRDDLGym until later (line 31).

Moving the try/except matplotlib import blocks below the pyRDDLGym imports block seems to work, not sure if that can cause other issues though.

**Comment by mike-gimelfarb** [comment]
Nice catch; Yes, you are right, the import for raise_warning should be above the try block. We wanted to raise a warning but will get an exception instead!

**Comment by iliathesmirnov** [comment]
Yep. That actually happened when running in a remote shell. Should be good now.
