### ISSUE TITLE
Tensorflow dependency probably not necessary

### ISSUE THREAD

**Issue by nhuet** [pyrddlgym-project/pyRDDLGym-jax#4]
When installing pyRDDLGym-jax, the whole tensorflow library is installed (as required by requirements.txt) but it seems in the code that only tensorflow-probability is used which is very light and does not require actually tensorflow. See https://www.tensorflow.org/probability/examples/TensorFlow_Probability_on_JAX

The only dependencies of tensorflow-probabilities are:

> ├── tensorflow-probability [required: >=0.21.0, installed: 0.24.0]
> │   ├── absl-py [required: Any, installed: 2.1.0]
> │   ├── cloudpickle [required: >=1.3, installed: 3.1.0]
> │   ├── decorator [required: Any, installed: 5.1.1]
> │   ├── dm-tree [required: Any, installed: 0.1.8]
> │   ├── gast [required: >=0.3.2, installed: 0.6.0]
> │   ├── numpy [required: >=1.13.3, installed: 1.26.4]
> │   └── six [required: >=1.10.0, installed: 1.16.0]

(as shown by pipdeptree tool on my dev environment)

Would it be possible to remove tensorflow from requirements? (If I correctly understood that it is not mandatory of course)

**Comment by mike-gimelfarb** [comment]
That's great to know! I will publish version 0.4 on pypi whenever I get a chance. The github version should install fine now.
